bot-token: 

bot:
  # ONLINE, DND, IDLE, INVISIBLE, OFFLINE
  status: ONLINE
  activity: true
  # WATCHING, PLAYING, LISTENING, STREAMING, COMPETING, CUSTOM
  activity-type: WATCHING
  activity-text: "Your Server"
  streaming-link: "https://twitch.tv/NotAMojangDev"

# Chat Channel
mc-chat-channel: <ID>

# Whitelist Channel
# whitelist-channel: 1089863344430776380
